import time
from uuid import uuid4

from app.schemas.model_calls import ModelCallRequest, ModelCallResult
from app.services.model_router import model_router
from app.services.store import now, store


class ModelGateway:
    def invoke(self, request: ModelCallRequest) -> ModelCallResult:
        started = time.perf_counter()
        route = model_router.route(request)
        response = self._dry_run_response(request, route.model)
        latency_ms = int((time.perf_counter() - started) * 1000)
        input_tokens = max(1, len(request.prompt.split()))
        output_tokens = max(1, len(response.split()))
        result = ModelCallResult(
            id=uuid4(),
            job_id=request.job_id,
            task_id=request.task_id,
            provider_id=route.provider_id,
            provider_type=route.provider_type,
            provider_name=route.provider_name,
            model=route.model,
            purpose=request.purpose,
            status="dry_run" if request.dry_run else "queued",
            prompt_preview=request.prompt[:500],
            response_preview=response[:1000],
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            estimated_cost_usd=round((input_tokens + output_tokens) * 0.000002, 6),
            latency_ms=latency_ms,
            metadata_json={
                "route_reason": route.reason,
                "response_schema": request.response_schema,
                "dry_run": request.dry_run,
            },
            created_at=now(),
        )
        store.add_model_call(result)
        store.add_event(
            request.job_id,
            "model_call.recorded",
            f"{route.provider_name} selected for {request.purpose}.",
            {"model_call_id": str(result.id), "provider_type": route.provider_type, "model": route.model},
        )
        return result

    def _dry_run_response(self, request: ModelCallRequest, model: str) -> str:
        if request.purpose == "planning":
            return (
                "{"
                f'"goal":"{request.prompt[:120]}",'
                '"tasks":["analyze_repo","design_changes","implement","validate"],'
                f'"model":"{model}",'
                '"mode":"dry_run"'
                "}"
            )
        return f"Dry-run {request.purpose} response generated by route target {model}."


model_gateway = ModelGateway()

